### ISSUE TITLE
Error to upload files to vimeo

### ISSUE THREAD

**Issue by mayander30** [bo-oz/vimeo_me2#43]
EXAMPLE: 
file = File.open("#{Rails.root}/public/recording/test/video.mp4")
@token = Rails.application.credentials.dig(:vimeo, :token)
@vimeo_client = VimeoMe2::User.new(@token)
@vimeo_client.upload_video(file)

the video is uploaded but return error.

<div class="content">
		<h1>Something went wrong</h1>
		<p>To continue, contact our <a href="mailto:support@vimeo.com">support team</a> (make sure you have your IP address), and mention code <code>W4A0F6</code>.</p>
	</div>

**Comment by proud-muraoka** [comment]
me too...

```
2022-01-21T02:45:18Z 10 TID-gt21jtwx4 ERROR: /usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
 /usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/http/http_request.rb:112:in `validate_response!'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/http/http_request.rb:26:in `make_http_request'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/base.rb:38:in `request'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/base.rb:18:in `block (2 levels) in <class:VimeoObject>'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/video.rb:58:in `update'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/user/upload.rb:35:in `change_name_and_get_video'
 /usr/local/bundle/bundler/gems/vimeo_me2-23fecd8dbe36/lib/vimeo_me2/user/upload.rb:12:in `upload_video'
```

**Comment by mayander30** [comment]
seems the upload files is not working more, only works pull_upload by the link

**Comment by isaeviv** [comment]
Did you manage to find any solution?

**Comment by mayander30** [comment]
@isaeviv I am using pull_upload.. I save my file in public tmp files so it have a url https:://yourdomain/yourfile. it works to me.

**Comment by martin16877** [comment]
I had the same problem and couldn't figure out what was wrong. I already started a fork of this lib to add some logging and find out what was happening. 

Then I generated a new token with more rights (not only the upload one but most of the others too) and now it seems to work!

<img width="674" alt="Schermafbeelding 2023-08-14 om 16 17 55" src="https://github.com/bo-oz/vimeo_me2/assets/66715/738d3bea-ce35-45ce-ab5a-3af1e026b681">
